# Generated by Django 5.2 on 2025-06-08 23:56

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.CharField(default=myapp.models.generate_random_string, editable=False, primary_key=True, serialize=False, unique=True)),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_desc', models.CharField(max_length=1000)),
                ('onActive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=myapp.models.generate_random_string, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=10000, null=True)),
                ('public_id', models.CharField(blank=True, max_length=3000, null=True)),
                ('original_name', models.CharField(blank=True, max_length=3000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(default=myapp.models.generate_random_string, editable=False, primary_key=True, serialize=False, unique=True)),
                ('medicine_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('medicine_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('suppositories', 'Suppositories'), ('drops', 'Drops'), ('inhalers', 'Inhalers'), ('injections', 'Injections'), ('implants', 'Implants'), ('creams', 'Creams'), ('patches', 'Patches')], max_length=50)),
                ('medicine_measurement', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=100)),
                ('onActive', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleUpload',
            fields=[
                ('id', models.CharField(default=myapp.models.generate_random_string, editable=False, primary_key=True, serialize=False, unique=True)),
                ('public_id', models.CharField(blank=True, max_length=3000, null=True)),
                ('original_name', models.CharField(blank=True, max_length=3000, null=True)),
                ('url', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
            ],
        ),
    ]
