# Generated by Django 5.2 on 2025-04-03 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                ("medicine_desc", models.CharField(max_length=1000)),
                ("onActive", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_price", models.FloatField()),
                ("quantity", models.IntegerField()),
                (
                    "medicine_type",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "capsule"),
                            ("liquid", "Liquid"),
                            ("suppositories", "Suppositories"),
                            ("drops", "Drops"),
                            ("inhalers", "Inhalers"),
                            ("injections", "Injections"),
                            ("implants", "Implants"),
                            ("creams", "Creams"),
                            ("patches", "Patches"),
                        ],
                        max_length=50,
                    ),
                ),
                ("medicine_measurement", models.CharField(max_length=50)),
                ("manufacturer", models.CharField(max_length=100)),
                ("onActive", models.BooleanField(default=True)),
                ("expiration_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "medicine_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.medicine"
                    ),
                ),
            ],
        ),
    ]
