# Generated by Django 5.2 on 2025-06-10 01:32

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.CharField(default=myapp.models.generate_random_string, editable=False, primary_key=True, serialize=False, unique=True)),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_desc', models.CharField(max_length=1000)),
                ('onActive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=myapp.models.generate_random_string, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=10000, null=True)),
                ('public_id', models.CharField(blank=True, max_length=3000, null=True)),
                ('original_name', models.CharField(blank=True, max_length=3000, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(default=myapp.models.generate_random_string, editable=False, primary_key=True, serialize=False, unique=True)),
                ('medicine_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('medicine_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('suppositories', 'Suppositories'), ('drops', 'Drops'), ('inhalers', 'Inhalers'), ('injections', 'Injections'), ('implants', 'Implants'), ('creams', 'Creams'), ('patches', 'Patches')], max_length=50)),
                ('medicine_measurement', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=100)),
                ('onActive', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleUpload',
            fields=[
                ('id', models.CharField(default=myapp.models.generate_random_string, editable=False, primary_key=True, serialize=False, unique=True)),
                ('public_id', models.CharField(blank=True, max_length=3000, null=True)),
                ('original_name', models.CharField(blank=True, max_length=3000, null=True)),
                ('url', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
            ],
        ),
    ]
