# Generated by Django 5.2 on 2025-04-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_user_id"),
    ]

    operations = []
