# Generated by Django 5.2 on 2025-04-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_auto_20250403_1629"),
    ]

    operations = []
