# Generated by Django 5.2 on 2025-04-05 05:44

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="id",
            field=models.CharField(
                default=myapp.models.generate_random_string,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="id",
            field=models.CharField(
                default=myapp.models.generate_random_string,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="onActive",
            field=models.BooleanField(default=False),
        ),
    ]
