# Generated by Django 5.2 on 2025-04-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_inventory_id_alter_medicine_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="medicine_type",
            field=models.CharField(
                choices=[
                    ("tablet", "Tablet"),
                    ("capsule", "Capsule"),
                    ("liquid", "Liquid"),
                    ("suppositories", "Suppositories"),
                    ("drops", "Drops"),
                    ("inhalers", "Inhalers"),
                    ("injections", "Injections"),
                    ("implants", "Implants"),
                    ("creams", "Creams"),
                    ("patches", "Patches"),
                ],
                max_length=50,
            ),
        ),
    ]
