# Generated by Django 5.2 on 2025-04-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_user_image_alter_inventory_medicine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="original_name",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="public_id",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
