# Generated by Django 5.2 on 2025-04-14 01:29

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_user_original_name_user_public_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageMultipleMedicine",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=myapp.models.generate_random_string,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("public_id", models.CharField(blank=True, max_length=3000, null=True)),
                (
                    "original_name",
                    models.CharField(blank=True, max_length=3000, null=True),
                ),
                ("url", models.CharField(blank=True, max_length=10000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.medicine"
                    ),
                ),
            ],
        ),
    ]
